### ISSUE TITLE
bug: Cant't extract data from extractor

### ISSUE THREAD

**Issue by locez** [0xPlaygrounds/rig#354]
- [x] I have looked for existing issues (including closed) about this

## Bug Report

I use extractor to get data from LLM but it always returns Err(Nodata).
Manually using agent to get json deserialized to struct works fine.

## Reproduction

```rust
use rig::providers::openai;
use schemars::JsonSchema;

#[derive(Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct VideoMetadata {
    pub title: String,
    pub season: Option<u32>,
    pub episode: Option<u32>,
}

#[tokio::main]
async fn main() {
   // use https://www.volcengine.com service
    let client = openai::Client::from_url(
        "TOKEN",
        "https://ark.cn-beijing.volces.com/api/v3",
    );

  // use deekseek-v3 or other model not work too
    let extractor = client
        .extractor::<VideoMetadata>("deepseek-v3-241226")
        .preamble("你是一个专业的视频元数据提取助手。你的任务是从视频文件名中提取标题、季数和集数。请分析文件名并提取这些信息。")
        .build();

    let filename =
        "[Airota&VCB-Studio] Yuru Camp Season 3 [01][Ma10p_1080p][x265_flac].mkv".to_string();

    let result = extractor.extract(&filename).await;
    println!("{:?}", result)
}

```
`cargo.toml`

```toml
[package]
name = "bug-report"
version = "0.1.0"
edition = "2024"

[dependencies]
rig-core = "0.9.1"
schemars = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full", "macros", "rt-multi-thread"] }
```

## Expected behavior

extractor can extract correctly

## Screenshots

![Image](https://github.com/user-attachments/assets/681a7983-868c-46dc-b22e-e9839aa43e22)
