### ISSUE TITLE
feat: Add a dedicated provider for LlamaEdge to empower the Gaia Network

### ISSUE THREAD

**Issue by ghost** [0xPlaygrounds/rig#468]
## Model Provider Integration Request

**LlamaEdge** is a WebAssembly-native AI inference runtime developed by Second State. It provides OpenAI-compatible APIs and can run entirely in-browser, at the edge, or inside Gaia decentralized inference nodes. This allows seamless integration of open-source LLMs, vision models, and speech tools into decentralized applications with minimal latency and high transparency.

**Gaia Network** supports LlamaEdge as a backend runtime, enabling Rig to offload inference to distributed nodes using a trustless, auditable protocol. This offers decentralized redundancy, cryptographic traceability of results, and the ability to run inference in regulated or offline environments.

### Supported Model Families

* **Text / Chat Completion**: LLaMA 2, LLaMA 3, CodeLLaMA, Baichuan, Mistral, Phi, TinyLlama (GGUF format)
* **Embeddings**: All MiniLM / BGE open models (e5-large, all-MiniLM-L6-v2, etc.)
* **Audio**: Whisper (transcription)
* **Image**: Stable Diffusion (generation via `/v1/images/generations`)
* **Multimodal**: CLIP embeddings and potential for LLaVA-style models

### Endpoints

* `POST /v1/chat/completions`
* `POST /v1/completions`
* `POST /v1/embeddings`
* `POST /v1/audio/transcriptions`
* `POST /v1/images/generations`

### Features

* OpenAI API-compatible interface
* Supports **streaming** via Server-Sent Events (SSE)
* Can run inference **locally**, on the **Gaia network**, or in **WASM VMs**
* Can run on CPU/WebAssembly with no GPU required
* Auth optional, supports rate limiting and load balancing

---

### Resources

* **GitHub – LlamaEdge**: [https://github.com/second-state/LlamaEdge](https://github.com/second-state/LlamaEdge)
* **Gaia Network - OpenAI-compatible API integration guide**: [https://docs.gaianet.ai/agent-integrations/intro/](https://docs.gaianet.ai/agent-integrations/intro/)

**Comment by ghost** [comment]
The exact incompatibility reason is still under investigation. However, a temporary workaround is to use TensorZero, which seemingly normalizes the API. It also supports field remapping with schema, but it was apparently not required.

## Initialization and Startup

1. Initialize your GaiaNet node:
   ```sh
   gaianet init
   ```

2. Start your node using the following command:
   ```sh
   gaianet start
   ```

3. After starting node, a successful start will print a public URL for the node.

Example URL: https://0xf63939431ee11267f4855a166e11cc44d24960c0.gaia.domain

## Configuration File

```toml
[gateway]
bind_address = "0.0.0.0:3000"

[models."my_gaia_model"]
routing = ["gaia_local"]

[models."my_gaia_model".providers.gaia_local]
type = "openai"
model_name = "Llama-3.2-3B-Instruct"
api_base = "https://0xf63939431ee11267f4855a166e11cc44d24960c0.gaia.domains/v1"
api_key_location = "none"

[functions.default_chat]
type = "chat"

[functions.default_chat.variants.default]
type = "chat_completion"
model = "my_gaia_model"
weight = 1.0
```

## Rust Code Example

```rust
use rig::client::completion::CompletionClientDyn;
use rig::{completion::Prompt, providers::openai};

#[tokio::main]
async fn main() {
    // Point to the middleware instead of GaiaNet or TensorZero directly
    let openai_client = openai::Client::from_url("", "http://localhost:3000/openai/v1");
    let gpt4 = openai_client
        .agent("tensorzero::model_name::my_gaia_model")
        .build();

    // Prompt the model and print its response
    let response = gpt4
        .prompt("Who are you?")
        .await
        .expect("Failed to prompt GPT-4");

    println!("GPT-4: {response}");
}
```
